# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "tinyRobot"
  limits:
    linear: [0.5, 0.75] # velocity, acceleration
    angular: [0.6, 2.0] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 0.3 # radius in m
    vicinity: 0.5 # radius in m
  reversible: True # whether robots in this fleet can reverse
  battery_system:
    voltage: 12.0 # V
    capacity: 24.0 # Ahr
    charging_current: 5.0 # A
  mechanical_system:
    mass: 20.0 # kg
    moment_of_inertia: 10.0 #kgm^2
    friction_coefficient: 0.22
  ambient_system:
    power: 20.0 # W
  tool_system:
    power: 0.0 # W
  recharge_threshold: 0.10 # Battery level below which robots in this fleet will not operate
  recharge_soc: 1.0 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  publish_fleet_state: 10.0 # Publish frequency for fleet state, ensure that it is same as robot_state_update_frequency
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: True
  actions: ["teleop", "manual_control", "identification"]
  finishing_request: "charge" # [park, charge, nothing]
  responsive_wait: True # Should responsive wait be on/off for the whole fleet by default? False if not specified.
  reassign_task_interval: 120 # seconds, specify how often a task reassignment should be triggered in the fleet
  robots:
    tinyRobot1:
        charger: "dock_1"
        responsive_wait: True # Should responsive wait be on/off for this specific robot? Overrides the fleet-wide setting.

    tinyRobot2:
        charger: "dock_2"
        responsive_wait: True # Should responsive wait be on/off for this specific robot? Overrides the fleet-wide setting. 

    tinyRobot3:
        charger: "dock_3"
        responsive_wait: True # Should responsive wait be on/off for this specific robot? Overrides the fleet-wide setting. 

    tinyRobot4:
        charger: "dock_4"
        responsive_wait: True # Should responsive wait be on/off for this specific robot? Overrides the fleet-wide setting. 

    tinyRobot5:
        charger: "dock_5"
        responsive_wait: True # Should responsive wait be on/off for this specific robot? Overrides the fleet-wide setting. 

    tinyRobot6:
        charger: "dock_6"
        responsive_wait: True # Should responsive wait be on/off for this specific robot? Overrides the fleet-wide setting. 

    tinyRobot7:
        charger: "dock_7"
        responsive_wait: True # Should responsive wait be on/off for this specific robot? Overrides the fleet-wide setting. 

    tinyRobot8:
        charger: "dock_8"
        responsive_wait: True # Should responsive wait be on/off for this specific robot? Overrides the fleet-wide setting. 

    tinyRobot9:
        charger: "dock_9"
        responsive_wait: True # Should responsive wait be on/off for this specific robot? Overrides the fleet-wide setting. 

    tinyRobot10:
        charger: "dock_10"
        responsive_wait: True # Should responsive wait be on/off for this specific robot? Overrides the fleet-wide setting. 

    tinyRobot11:
        charger: "dock_11"
        responsive_wait: True # Should responsive wait be on/off for this specific robot? Overrides the fleet-wide setting. 

    tinyRobot12:
        charger: "dock_12"
        responsive_wait: True # Should responsive wait be on/off for this specific robot? Overrides the fleet-wide setting. 

    tinyRobot13:
        charger: "dock_13"
        responsive_wait: True # Should responsive wait be on/off for this specific robot? Overrides the fleet-wide setting. 

    tinyRobot14:
        charger: "dock_14"
        responsive_wait: True # Should responsive wait be on/off for this specific robot? Overrides the fleet-wide setting. 

    tinyRobot15:
        charger: "dock_15"
        responsive_wait: True # Should responsive wait be on/off for this specific robot? Overrides the fleet-wide setting. 

    tinyRobot16:
        charger: "dock_16"
        responsive_wait: True # Should responsive wait be on/off for this specific robot? Overrides the fleet-wide setting. 

    tinyRobot17:
        charger: "dock_17"
        responsive_wait: True # Should responsive wait be on/off for this specific robot? Overrides the fleet-wide setting. 

    tinyRobot18:
        charger: "dock_18"
        responsive_wait: True # Should responsive wait be on/off for this specific robot? Overrides the fleet-wide setting. 

    tinyRobot19:
        charger: "dock_19"
        responsive_wait: True # Should responsive wait be on/off for this specific robot? Overrides the fleet-wide setting. 

    tinyRobot20:
        charger: "dock_20"
        responsive_wait: True # Should responsive wait be on/off for this specific robot? Overrides the fleet-wide setting.

    tinyRobot21:
        charger: "dock_21"
        responsive_wait: True # Should responsive wait be on/off for this specific robot? Overrides the fleet-wide setting.

fleet_manager:
  ip: "127.0.0.1"
  port: 22011
  user: "some_user"
  password: "some_password"
