# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "tinyRobot"
  limits:
    linear: [0.5, 0.75] # velocity, acceleration
    angular: [0.6, 2.0] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 0.3 # radius in m
    vicinity: 0.5 # radius in m
  reversible: True # whether robots in this fleet can reverse
  battery_system:
    voltage: 12.0 # V
    capacity: 24.0 # Ahr
    charging_current: 5.0 # A
  mechanical_system:
    mass: 20.0 # kg
    moment_of_inertia: 10.0 #kgm^2
    friction_coefficient: 0.22
  ambient_system:
    power: 20.0 # W
  tool_system:
    power: 0.0 # W
  recharge_threshold: 0.10 # Battery level below which robots in this fleet will not operate
  recharge_soc: 1.0 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  publish_fleet_state: 10.0 # Publish frequency for fleet state, ensure that it is same as robot_state_update_frequency
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: True
    patrol: True
  actions: ["teleop", "manual_control", "tray_identification", "move_to", "jacking", "laser_back", "drop"]
  finishing_request: "charge" # [park, charge, nothing]
  responsive_wait: True # Should responsive wait be on/off for the whole fleet by default? False if not specified.
  reassign_task_interval: 120 # seconds, specify how often a task reassignment should be triggered in the fleet
  robots:
robots:
  F1PRO2.2D-231:
      charger: "F1PRO2.2D-231_charger"
      responsive_wait: True

  F1PRO2.2D-232:
      charger: "F1PRO2.2D-232_charger"
      responsive_wait: True

  F1PRO2.2D-233:
      charger: "F1PRO2.2D-233_charger"
      responsive_wait: True

  F1PRO2.2D-234:
      charger: "F1PRO2.2D-234_charger"
      responsive_wait: True

  F1PRO2.2D-235:
      charger: "F1PRO2.2D-235_charger"
      responsive_wait: True

  F1PRO2.2D-236:
      charger: "F1PRO2.2D-236_charger"
      responsive_wait: True

  F1PRO2.2D-237:
      charger: "F1PRO2.2D-237_charger"
      responsive_wait: True

  F1PRO2.2D-238:
      charger: "F1PRO2.2D-238_charger"
      responsive_wait: True

  F1PRO2.2D-239:
      charger: "F1PRO2.2D-239_charger"
      responsive_wait: True

  F1PRO2.2D-240:
      charger: "F1PRO2.2D-240_charger"
      responsive_wait: True

  F1PRO2.2D-241:
      charger: "F1PRO2.2D-241_charger"
      responsive_wait: True

  F1PRO2.2D-242:
      charger: "F1PRO2.2D-242_charger"
      responsive_wait: True

  F1PRO2.2D-243:
      charger: "F1PRO2.2D-243_charger"
      responsive_wait: True

  F1PRO2.2D-244:
      charger: "F1PRO2.2D-244_charger"
      responsive_wait: True

  F1PRO2.2D-245:
      charger: "F1PRO2.2D-245_charger"
      responsive_wait: True

  F1PRO2.2D-246:
      charger: "F1PRO2.2D-246_charger"
      responsive_wait: True

  F1PRO2.2D-247:
      charger: "F1PRO2.2D-247_charger"
      responsive_wait: True

  F1PRO2.2D-248:
      charger: "F1PRO2.2D-248_charger"
      responsive_wait: True

  F1PRO2.2D-249:
      charger: "F1PRO2.2D-249_charger"
      responsive_wait: True

  F1PRO2.2D-250:
      charger: "F1PRO2.2D-250_charger"
      responsive_wait: True

  F1PRO2.2D-251:
      charger: "F1PRO2.2D-251_charger"
      responsive_wait: True

  F1PRO2.2D-252:
      charger: "F1PRO2.2D-252_charger"
      responsive_wait: True

  F1PRO2.2D-253:
      charger: "F1PRO2.2D-253_charger"
      responsive_wait: True

  F1PRO2.2D-254:
      charger: "F1PRO2.2D-254_charger"
      responsive_wait: True
fleet_manager:
  ip: "127.0.0.1"
  port: 22011
  user: "some_user"
  password: "some_password"
